// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0_msrYFw56ggNjg7hXiDwtzmDtmlkUec',
    appId: '1:309762707392:web:08f181ba09db711d288225',
    messagingSenderId: '309762707392',
    projectId: 'note-app-2024',
    authDomain: 'note-app-2024.firebaseapp.com',
    storageBucket: 'note-app-2024.appspot.com',
    measurementId: 'G-63GQFL0Q09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTXfXsdRukQAxiJPb9PudCiosF1vgPNj4',
    appId: '1:309762707392:android:352f322df8d9bea4288225',
    messagingSenderId: '309762707392',
    projectId: 'note-app-2024',
    storageBucket: 'note-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8gORcJacCFqrE9B76fZemFqQsMPBp6SI',
    appId: '1:309762707392:ios:44d2aff7d6895229288225',
    messagingSenderId: '309762707392',
    projectId: 'note-app-2024',
    storageBucket: 'note-app-2024.appspot.com',
    iosBundleId: 'com.noteapp.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8gORcJacCFqrE9B76fZemFqQsMPBp6SI',
    appId: '1:309762707392:ios:db0f2c70366bd6f4288225',
    messagingSenderId: '309762707392',
    projectId: 'note-app-2024',
    storageBucket: 'note-app-2024.appspot.com',
    iosBundleId: 'com.noteapp.noteApp.RunnerTests',
  );
}
